version: '2'
services:

  airplane-glue:
    image: airplane-glue:latest
    depends_on:
        - airplane-glue-router
        - wikipedia-adapter
    ports:
      - "80:80"

  airplane-glue-router:
    image: airplane-glue-router:latest
    environment:
      NODE_ENV: production
      PORT: 3000
      WIKIPEDIA_URL: wikipedia-adapter:3001
    volumes:
      - ./seed.n3:/usr/src/seed.n3
    restart: always

  wikipedia-adapter:
    image: wikipedia-adapter:latest
    environment:
      PORT: 3001
    restart: always
